[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 100_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
